MovieShop.MVC/Controllers/CastController.cs
using MovieShop.Entities;
using MovieShop.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MovieShop.MVC.Controllers
{
    public class CastController : Controller
    {
        private readonly ICastService _castService;

        public CastController(ICastService castService)
        {
            _castService = castService;
        }
        // GET: Cast
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        //
        [HttpPost]
        //public ActionResult Create(string castname, string profilePath, string gender, string tmdbUrl)
        public ActionResult Create(Cast cast)
        {
            _castService.AddCast(cast);
            return View();
        }
    }
}

MovieShop.MVC/Controllers/GenresController.cs
using MovieShop.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MovieShop.MVC.Controllers
{
    public class GenresController : Controller
    {
        private readonly IGenreService _genreService;
        // GET: Genres
        public GenresController(IGenreService genreService)
        {
            _genreService = genreService;
        }

        public PartialViewResult Index()
        {
            var genres = _genreService.GetAllGenres().OrderBy(g => g.Name).ToList();
            return PartialView("GenresView", genres);
            //return View(genres);
        }
    }
}

MovieShop.MVC/Controllers/HomeController.cs
using MovieShop.MVC.Filters;
using MovieShop.Services;
using NLog;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MovieShop.MVC.Controllers
{
    [MovieShopExceptionFilter]
    public class HomeController : Controller
    {
        private readonly IMovieService _movieService;
        public HomeController(IMovieService movieService)
        {
            _movieService = movieService;
        }

        //[LogActionFilter]
        //[MovieShopExceptionFilter]
        //[HandleError]
        public ActionResult Index()
        {
            //int x = 0;
            //int y = 5;
            //int z = y / x;

            var movies = _movieService.GetTopGrossingMovies();
            return View(movies);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MovieShop.MVC/Controllers/MoviesController.cs
using MovieShop.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MovieShop.MVC.Controllers
{
    [RoutePrefix("movies")]
    public class MoviesController : Controller
    {
        private readonly IMovieService _movieService;
        public MoviesController(IMovieService movieService)
        {
            //pass a object that implements the interface
            //MVC 5 requires parameterless constructor
            //but we need DI
            _movieService = movieService;
        }
        // GET: Movies
        //Routing
        [HttpGet]
        //[Route("")]
        public ActionResult Index()
        {
            var movies = _movieService.GetTopGrossingMovies();
            return View(movies);
            //return View("test"); //return the view with different name
        }

        
        //[HttpGet]
        [Route("genres/{genreId}")]
        public ActionResult GenreMovies(int genreId)
        {
            //take genre id from url and then call movie service to get a list of movies
            //belonging to that genre.
            // return movies to the View and display as Imagetags inside the
            //bootstrap card with image urls as posterUrl from Movie table column
            // Create GetMoviesByGenre(int genreId) inside IMovieService and
            // implement that method call Movies Repository to get movies of that genre
            var movies = _movieService.GetMoviesByGenre(genreId).OrderBy(m=>m.Title).ToList();
            return View("MoviesByGenre",movies);
        }
    }
}

MovieShop.MVC/Views/Cast/Create.cshtml
@model MovieShop.Entities.Cast

@{
    ViewBag.Title = "Create";
}

<h2>View</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Cast</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TmdbUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TmdbUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TmdbUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProfilePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProfilePath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProfilePath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MovieShop.MVC/Views/Cast/OldCreate.cshtml
@{
    ViewBag.Title = "Create";
}

<h2>Create Cast</h2>

<form method="post">
    Name: <input type="text" name="name" id="name" value="" /><br />
    Gender: <input type="text" name="gender" id="gender" value="" /><br />
    Tmdb Url: <input type="text" name="tmdbUrl" id="tmdbUrl" value="" /><br />
    Profile Path: <input type="text" name="profilePath" id="profilePath" value="" /><br />

    <input type="submit" name="save" value="Save Cast" />
</form>

MovieShop.MVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MovieShop.MVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MovieShop.MVC/Views/Home/Index.cshtml
@model IEnumerable<MovieShop.Entities.Movie>
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="rounded">
    <div class="container-fluid bg-light">
        <div class="row">
            @foreach (var movie in Model)
            {
                <div class="col-6 col-lg-3 col-sm-4 col-xl-2">
                    @Html.Partial("_MovieCard", movie)
                </div>

            }
        </div>
    </div>
</div>

MovieShop.MVC/Views/Movies/Index.cshtml
@model List<MovieShop.Entities.Movie>

@{ 
    ViewBag.Title = "Index";
}

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h1>Top Revenue Movies, Grace</h1>

<table class="table">
    <tr>
        <td>Id</td>
        <td>Title</td>
        <td>Revenue</td>
        <td>Budget</td>
    </tr>

    <tbody>
        @foreach(var movie in Model)
        {
            <tr>
                <td>@movie.Id</td>
                <td>@movie.Title</td>
                <td>@movie.Revenue</td>
                <td>@movie.Budget</td>
            </tr>
        }
    </tbody>
</table>

MovieShop.MVC/Views/Movies/MoviesByGenre.cshtml
@model IEnumerable<MovieShop.Entities.Movie>
@{
    ViewBag.Title = "MoviesByGenre";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="rounded">
    <div class="container-fluid bg-light">
        <div class = "row">
            @foreach (var movie in Model)
            {
            <div class="col-6 col-lg-3 col-sm-4 col-xl-2">
                @Html.Partial("_MovieCard", movie)
            </div>
               
            }
        </div>
    </div>
</div>

MovieShop.MVC/Views/Shared/GenresView.cshtml
@model IEnumerable<MovieShop.Entities.Genre>

@foreach (var genre in Model)
{
    @Html.ActionLink(genre.Name, "GenreMovies", "Movies", new { genreId = genre.Id }, new { @class = "dropdown-item" })
}

MovieShop.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top ">
        @Html.ActionLink("MovieStore", "Index", "Home", new { area = "" }, new { @class = "navbar-brand", id = "movieTest" })
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown">
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        @Html.ActionLink("Top Movies", "Genre", "Movies", "", new { @class = "dropdown-item" })
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Genres
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        @{ Html.RenderAction("Index", "Genres"); }
                    </div>
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Login", "User", "SignIn", null, new { @class = "btn btn-outline-primary rounded-pill" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("SignUp", "User", "SignUp", null, new { @class = "btn btn-primary rounded-pill" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("About", "About", "Home", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Contact", "Contact", "Home", null, new { @class = "nav-link" })
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search Movies" aria-label="Search">
                <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MovieShop.MVC/Views/Shared/_MovieCard.cshtml
@model MovieShop.Entities.Movie

<div class="card mb-4 shadow bg-light">
    <img class="img-fluid" src=@Url.Content(Model.PosterUrl) alt="Card image cap Responsive">
    @*<div class="card-body">
        <h5 class="card-title">@Model.Title</h5>
    </div>*@
</div>